
[rooms]
	room_secrets = 0
	room_names = 1
	found_room_secrets = 0
	color_text = false
	room_checkmarks = 1

	[rooms.checkmarks]
		center_room_checkmarks = true

	[rooms.text]
		center_room_names = true

[other_features]

	[other_features.wither_door]
		has_key_color = "255,0,255,0"
		no_key_color = "255,255,0,0"
		door_fill_opacity = 0.25
		box_wither_doors = false
		door_outline_width = 3.0
		door_outline_opacity = 1.0

[map]

	[map.size]
		map_text_scale = 0.75
		player_name_scale = 0.8
		player_heads_scale = 1.0

	[map.toggle]
		vanilla_head_marker = false
		center_map = false
		dynamic_rotate = false
		rotate_map = false
		map_enabled = false
		show_player_names = 0
		hide_in_boss = false

	[map.render]
		map_border_color = "255,0,0,0"
		border_thickness = 3.0
		map_background_color = "100,0,0,0"

[colors]

	[colors.doors]
		entrance_door = "255,20,133,0"
		opened_wither_door = "255,92,52,14"
		blood_door = "255,231,0,0"
		wither_door = "255,0,0,0"
		unopened_door = "255,65,65,65"
		normal_door = "255,92,52,14"

	[colors.rooms]
		rare_room = "255,255,203,89"
		unopened_room = "255,65,65,65"
		blood_room = "255,255,0,0"
		fairy_room = "255,224,0,255"
		entrance_room = "255,20,133,0"
		puzzle_room = "255,117,0,133"
		normal_room = "255,107,58,17"
		trap_room = "255,216,127,51"
		miniboss_room = "255,254,223,0"

