
[pets]

	[pets.displays]
		cap_dolphin_pet_display = true
		dolphin_pet_display = false

	[pets.quality_of_life]
		highlight_favorite_pets = true
		favorite_pet_highlight_color = "255,0,255,255"
		highlight_active_pet = true
		active_pet_highlight_color = "255,0,255,0"
		autopet_message_hider = 0
		hide_pet_nametags = false
		pet_item_confirmation = false

[general]

	[general.other]
		always_sprint_in_skyblock = false
		config_button_on_pause = true
		reopen_options_menu = true
		first_launch = false
		last_launched_skytils_version = "1.10.7-RC1"

	[general.reparty]
		override_other_reparty_commands = true
		auto-accept_reparty_timeout = 60
		auto-accept_reparty = true

	[general.local_api]
		auto_start_local_api = false
		local_api_password = ""

	[general.command_aliases]
		command_alias_subcommands = false
		command_alias_mode = 1

	[general.api]
		hypixel_api_key = "76aabe20-3c96-4638-8aae-bf372c24603b"
		fetch_kuudra_prices = false
		fetch_lowest_bin_prices = false
		connect_to_skytils_ws_server = true

	[general.hypixel]
		multiple_party_invites_fix = false
		guild_leave_confirmation = true
		coop_add_confirmation = true

	[general.updates]
		update_channel = 2

[miscellaneous]

	[miscellaneous.other]
		show_selected_arrow = false
		dupe_tracker = true
		hide_tooltips_while_on_storage = false
		ping_display = 0
		also_copy_very_rare_drops_to_clipboard = false
		transparent_armor_layer = 1.0
		auto_copy_rng_drops_to_clipboard = false
		random_stuff = false
		players_in_range_display = false
		"mark_'dirty'_items" = true
		head_layer_transparency = 1.0
		cap_legion_display = true
		scam_check = true
		legion_player_display = false
		show_bestiary_level = false
		transparent_head_layer = 1.0
		show_world_age = false
		fix_summon_skin = false
		use_player_skin = false
		copy_deaths_to_clipboard = false
		dupe_tracker_overlay_color = "169,0,0,0"
		endstone_protector_spawn_timer = false
		placed_summoning_eye_display = false

	[miscellaneous.brewing]
		color_brewing_stands = false

	[miscellaneous.chat_tabs]
		chat_tabs = false
		pre-fill_chat_commands = false
		copy_chat_messages = false
		auto_switch_chat_channel = false

	[miscellaneous.items]
		price_paid = false
		show_npc_sell_price = false
		item_stars_display = 0
		dropped_item_scale = 1.0
		show_dungeon_item_level = false
		show_attribute_shard_abbreviation = false
		wither_shield_cooldown_tracker = false
		hide_implosion_particles = true
		prevent_placing_weapons = true
		larger_heads = 1.0
		show_attribute_shard_level = false
		show_item_quality_ = false
		show_gemstones = false
		highlight_filled_bazaar_orders = false
		show_dungeon_floor_as_stack_size = false
		show_head_floor_number = false
		book_helper = false
		show_item_star_count = false
		hide_midas_staff_gold = false
		block_zapper_fatigue_timer = false
		combine_helper = false
		show_enchanted_book_abbreviation = false
		held_item_scale = 1.0
		item_cooldown_display = false
		head_display_size = 1.0
		show_potion_tier = false
		show_enchanted_book_tier = true
		show_new_year_cake_year = false
		stacking_enchant_progress_display = false
		show_pet_candies = false
		wither_shield_has_wither_impact = true
		show_etherwarp_teleport_position = false
		dropped_item_size = 1.0
		compact_item_stars = false
		radioactive_bonus = true
		disable_block_animation = false
		show_item_origin = false
		etherwarp_teleport_position_color = "69,0,0,255"

	[miscellaneous.fixes]
		prevent_log_spam = true
		twitch_fix = true
		boss_bar_fix = true
		fix_world_time = true
		fix_falling_sand_rendering = false
		fix_sba_chroma = false

	[miscellaneous.item_rarity]
		item_rarity_shape = 2
		item_rarity_opacity = 0.75
		show_item_rarity = true
		show_pet_rarity = true
		item_rarity_transparency = 0.75

	[miscellaneous.minions]
		only_collect_enchanted_items = false
		show_minion_tier = true

	[miscellaneous.quality_of_life]
		hide_vanilla_health_display = false
		container_sell_value = false
		hide_cheap_coins = false
		hide_jerry_rune = false
		party_addons = false
		show_arachne_spawn = false
		show_lowest_bin_price = false
		trophy_fish_tracker = false
		dungeon_pot_lock = 0
		hide_hunger_display = false
		include_item_modifiers = true
		hide_fire_on_entities = false
		highlight_salvageable_items = false
		hide_pet_health_display = false
		no_hurtcam = true
		power_orb_lock = false
		show_coins_per_bit = false
		hide_fishing_hooks = false
		stop_clicking_non-salvageable_items = false
		show_trophy_fish_totals = false
		show_coins_per_copper = false
		"spider's_den_rain_timer" = false
		view_relic_waypoints = false
		stop_hook_sinking_in_lava = true
		restock_arrows_warning = 0
		always_show_item_name_highlight = false
		hide_air_display = true
		power_orb_lock_duration = 10
		comma_damage = false
		fishing_hook_age = false
		find_rare_relics = false
		hide_mob_death_particles = true
		hide_lightning = false
		disable_night_vision = true
		no_fire = false
		show_arachne_hp = false
		tropy_fish_tracker = false
		custom_auction_price_input = false
		low_health_vignette_threshold = 0.0
		custom_damage_splash_style = 0
		protect_starred_items = false
		show_total_trophy_fish = false
		hide_scoreboard_score = false
		highlight_dungeon-sellable_items = false
		middle_click_gui_items = false
		highlight_disabled_potion_effects = true
		prevent_cursor_reset = false
		moveable_action_bar = false
		lower_enderman_nametags = false
		big_tentacle_nametags = false
		hide_absorption_hearts = false
		max_displayed_items = 20
		moveable_item_name_highlight = false
		prevent_moving_on_death = false
		custom_damage_splash = false
		enchant_glint_fix = true
		hide_players_in_spawn = false
		better_stash = false
		hide_potion_effects_in_inventory = false
		disable_enderman_teleportation = false
		hide_armor_display = false
		quiver_display = false
		low_health_vignette_color = "255,255,255,255"
		press_enter_to_confirm_sign_popups = true
		protect_items_above_value = "0"

[slayer]
	current_sven_rng_meter = 0.0
	current_inferno_rng_meter = 0.0
	twinclaw_alert = false
	vampire_slayer_one_shot_alert = false
	current_voidgloom_rng_meter = 0.0
	current_revenant_rng_meter = 0.0
	current_bloodfiend_rng_meter = 0.0
	current_tarantula_rng_meter = 0.0

	[slayer.general]
		use_hits_to_detect_slayer = true
		carry_mode = 0
		use_nametag_to_detect_slayer = false

	[slayer.inferno_demonlord]
		totem_ping = 0
		ping_when_in_inferno_demonlord_fire = false
		hide_pacified_blazes = true
		show_totem_display = true
		recolor_demonlord_boss_by_attunement = true

	[slayer.voidgloom_seraph]
		yang_glyph_highlight_color = "128,65,102,245"
		"hide_others'_broken_heart_radiation" = true
		seraph_beacon_phase_color = "255,0,254,255"
		highlight_nukekebi_fixation_heads = true
		point_to_yang_glyph = false
		seraph_hits_phase_color = "255,255,255,255"
		highlight_yang_glyph = true
		low_soulflow_ping = 100
		nukekebi_fixation_head_color = "128,65,102,245"
		seraph_normal_phase_color = "255,0,0,0"
		show_seraph_display = false
		yang_glyph_ping_on_land = true
		show_soulflow_display = false
		recolor_seraph_boss = true
		yang_glyph_ping = true

	[slayer.quality_of_life]
		show_slayer_display = false
		slayer_miniboss_spawn_alert = true
		slayer_boss_hitbox = false
		show_slayer_armor_kills = false
		click_to_open_maddox_menu = false
		show_rngesus_meter = false
		show_slayer_time_to_kill = true
		ping_when_in_atoned_horror_danger_zone = false

[sounds]

	[sounds.abilities]
		disable_cooldown_sounds = false
		disable_jerry-chine_gun_sounds = false
		disable_flower_of_truth_sounds = false

	[sounds.dungeons]
		disable_terracotta_sounds = false

[kuudra]

	[kuudra.performance]
		hide_non-nametag_armor_stands_on_kuudra = false

	[kuudra.price_checking]
		kuudra_chest_profit_subtracts_key = true
		show_kuudra_lowest_bin_price = true
		kuudra_chest_profit = false
		kuudra_chest_profit_includes_essence = true

	[kuudra.quality_of_life]
		kuudra_auto-reparty_player = ""

[dungeons]

	[dungeons.party_finder]
		party_finder_stats = true
		"§b[wip]_§rparty_finder_stats" = false

	[dungeons.miscellaneous]
		auto_copy_fails_to_clipboard = false
		highlight_unopened_croesus_chests = false
		red_screen_fix = true
		sadan_phase_timer = false
		dungeon_timer = false
		hide_opened_croesus_chests = false
		show_decimal_seconds_on_timers = false
		necron_phase_timer = false
		death_counter = false
		dungeon_map = false
		dungeon_chest_profit_includes_essence = true
		dungeon_chest_profit = false
		dungeon_start_confirmation = false

	[dungeons.tank_helper_tools]
		tank_range_wall = true
		tank_range_wall_color = "50,100,255,0"
		boxed_tank_color = "255,0,255,0"
		tank_protection_range_display = false
		box_protected_teammates = false
		protected_teammate_box_color = "255,255,0,0"
		boxed_tanks = false

	[dungeons.hud]
		blood_room_portal_timer = false
		dungeon_crypts_counter = false

	[dungeons.terminal_solvers]
		predict_clicks_for_alignment_solver = true
		change_all_to_same_color_solver = true
		predict_clicks_for_simon_says_solver = false
		click_in_order_first_color = "255,2,62,138"
		change_all_to_same_color_solver_mode = 0
		click_in_order_third_color = "255,144,224,239"
		middle_click_on_terminals = false
		click_in_order_solver = true
		starts_with_sequence_solver = true
		shoot_the_target_solver = true
		item_frame_alignment_solver = true
		select_all_colors_solver = true
		click_in_order_second_color = "255,65,102,245"
		block_incorrect_terminal_clicks = false
		simon_says_solver = true

	[dungeons.score_calculation]
		300_title_message = ""
		send_message_on_300_score = true
		270_title_message = ""
		message_for_270_score = ""
		message_for_300_score = ""
		receive_score_calculation_party_assist = true
		create_title_on_270_score = false
		"allow_mimic_dead!_from_other_mods" = false
		show_dungeon_score_estimate = true
		create_title_on_300_score = false
		minimized_dungeon_score_estimate = true
		score_calculation_party_assist = false
		send_message_on_270_score = true

	[dungeons.fixes]
		inject_fake_dungeon_map = false

	[dungeons.quality_of_life]
		hide_fairies = false
		dungeon_secret_display = false
		show_bat_hitboxes = true
		auto-reparty_on_dungeon_ending = false
		hide_damage_in_boss = false
		hide_non-starred_mobs_nametags = true
		highlight_door_opener = false
		"change_hurt_color_on_the_wither_king's_dragons" = false
		"show_sadan's_interest" = false
		"show_wither_king's_dragons_hp" = false
		wither_king_dragon_spawn_alert = false
		hide_terminal_completion_titles = false
		hide_terracotta_nametags = false
		show_giant_hp = false
		show_terracotta_respawn_time = true
		say_blaze_done = true
		dungeon_chest_reroll_confirmation = 0
		hide_spirit_animal_nametags = false
		box_spirit_bow = false
		blood_camp_helper_color = "255,255,0,0"
		hide_wither_king_dragon_death = false
		"show_wither_king's_dragons'_hp" = false
		"show_necron's_hp" = 1
		"retexture_wither_king's_dragons" = false
		box_starred_mobs = false
		hide_dying_mobs = true
		spirit_leap_names = false
		hide_floor_4_crowd_messages = false
		larger_bat_models = true
		show_wither_king_statue_box = false
		box_starred_mobs_color = "255,0,255,255"
		blood_camp_helper = true
		revive_stone_names = false
		hide_wither_miner_nametags = true
		spirit_bear_timer = false
		spirit_pet_warning = false
		"show_wither_king's_dragons'_spawn_timer" = false
		box_spirit_bear = false
		box_skeleton_masters = false
		dungeon_chest_reroll_protection_threshold = 0
		show_guardian_respawn_timer = false
		hide_archer_bone_passive = false
		ghost_leap_names = false
		"show_wither_king's_dragons'_color_as_text" = false
		wither_king_dragon_dimensional_slash_alert = false
		hide_oruo_messages = false
		show_giant_hp_at_feet = false

	[dungeons.solvers]
		ice_fill_solver = true
		lowest_blaze_color = "200,255,0,0"
		next_blaze_color = "200,255,255,0"
		type_of_livid_finder = 0
		ice_path_solver = true
		teleport_maze_solver_color = "200,255,0,0"
		line_to_next_blaze = false
		line_to_next_blaze_color = "200,255,255,0"
		three_weirdos_solver_color = "255,255,0,0"
		trivia_solver = true
		highest_blaze_color = "200,0,255,0"
		blaze_solver = true
		boulder_solver = true
		show_next_blaze = true
		water_board_solver = true
		find_correct_livid = true
		tic_tac_toe_solver = true
		teleport_maze_solver = true
		creeper_beams_solver = true
		three_weirdos_solver = true
		tic_tac_toe_solver_color = "204,23,234,99"
		boulder_solver_color = "255,255,0,0"

[farming]

	[farming.garden]
		visitor_notifications = false
		visitor_offer_helper = false
		plot_cleanup_helper = false
		"show_sam's_scythe_blocks" = false
		"color_of_sam's_scythe_marked_blocks" = "50,255,0,0"

	[farming.quality_of_life]
		trapper_cooldown_alarm = false
		hide_farming_rng_titles = false
		click_to_accept_trapper_task = true
		"talbot's_theodolite_helper" = false

	[farming.solvers]
		treasure_hunter_solver = true
		hungry_hiker_solver = true

[mining]

	[mining.crystal_hollows]
		crystal_hollows_chat_coordinates_grabber = true
		crystal_hollows_death_waypoints = false
		crystal_hollows_waypoints = true
		king_yolkar_waypoint = true
		crystal_hollows_map_special_places = true
		crystal_hollows_treasure_helper = false
		crystal_hollows_map = true

	[mining.quality_of_life]
		powder_ghast_ping = false
		skymall_reminder = true
		raffle_warning = false
		dark_mode_mist = true
		recolor_carpets = false
		highlight_completed_commissions = true
		highlight_disabled_hotm_perks = true
		more_visible_ghosts = true
		raffle_waypoint = false

	[mining.solvers]
		puzzler_solver = false
		fetchur_solver = false

[spam]

	[spam.abilities]
		implosion_hider = 1
		ray_of_hope_hider = 0
		midas_staff_hider = 0
		mining_ability_hider = 1
		healing_message_hider = 0
		spirit_sceptre_hider = 0
		giant_sword_hider = 0
		livid_dagger_hider = 0
		mana_use_hider = 1

	[spam.miscellaneous]
		spook_message_hider = 0
		compact_hider = 0
		combo_hider = 0
		compact_mining_powder_gain = true
		no_enemies_nearby_hider = 0
		profile_message_hider = 0
		cooldown_hider = 0
		blocks_in_the_way_hider = 0
		auto-recombobulator_hider = 0
		out_of_mana_hider = 0
		pristine_hider = 0
		"can't_use_ability_hider" = 0
		wind_direction_hider = 0
		compact_building_tools = false

	[spam.display]
		text_shadow = 0

	[spam.dungeons]
		blessing_hider = 0
		boss_messages_hider = 0
		wither_essence_hider = 0
		superboom_pickup_hider = 0
		self_orb_pickup_hider = 0
		blood_key_hider = 0
		toast_time = 2500
		dungeon_abilities_messages_hider = 0
		tether_hider = 0
		other_orb_pickup_hider = 0
		countdown_and_ready_messages_hider = 0
		revive_stone_pickup_hider = 0
		wither_key_hider = 0
		undead_essence_hider = 0
		mort_messages_hider = 0
		trap_damage_hider = 0

	[spam.fishing]
		blessed_bait_hider = 0
		blessing_enchant_hider = 0
		sea_creature_catch_hider = 0
		good_fishing_treasure_hider = 0
		legendary_sea_creature_catch_hider = 0
		great_fishing_treasure_hider = 0

[events]

	[events.mayor_jerry]
		track_mayor_jerry_items = false
		hidden_jerry_timer = false
		hidden_jerry_alert = false
		display_jerry_perks = false

	[events.mythological]
		treasure_burrow_color = "255,173,216,230"
		display_gaia_construct_hits = false
		track_mythological_creatures = false
		"empty/start_burrow_color" = "255,173,216,230"
		ping_when_burrow_is_nearby = false
		"griffin_burrow_estimation_(meow)" = false
		griffin_burrow_estimation = false
		broadcast_rare_drop_notifications = false
		show_griffin_burrows = false
		mob_burrow_color = "255,173,216,230"

	[events.spooky]
		trick_or_treat_chest_alert = false

	[events.technoblade]
		show_shiny_orb_waypoints = false
		show_shiny_pig_locations = false

